version: '3.0'

services:

  ugc-test:
    container_name: ugc-test
    build: ./
    
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db/
    ports:
      - 27017:27017

volumes:
  mongo_data: {}
