# Generated by Django 3.2.16 on 2022-10-28 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='task')),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], default='scheduled', max_length=255, null=True, verbose_name='status')),
                ('recipient_filter', models.JSONField(default={'email': 'to@example.com'})),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notify"."notifications',
            },
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True, verbose_name='recipient')),
                ('status_received', models.BooleanField(default=False, verbose_name='status_received')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
            ],
            options={
                'verbose_name': 'recipient',
                'verbose_name_plural': 'recipients',
                'db_table': 'notify"."recipients',
            },
        ),
        migrations.CreateModel(
            name='Senders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.TextField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'sender',
                'verbose_name_plural': 'senders',
                'db_table': 'notify"."senders',
            },
        ),
        migrations.CreateModel(
            name='TemplatesBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='text_template')),
                ('content_type', models.CharField(choices=[('html', 'html'), ('pdf', 'pdf'), ('markdown', 'markdown')], max_length=255, verbose_name='content_type')),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'body_template',
                'verbose_name_plural': 'body_templates',
                'db_table': 'notify"."templates_body',
            },
        ),
        migrations.CreateModel(
            name='TemplatesNotify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='theme')),
                ('notification_type', models.CharField(blank=True, choices=[('mail', 'mail'), ('sms', 'sms'), ('telegram', 'telegram'), ('viber', 'viber'), ('whatsapp', 'whatsapp'), ('push', 'push')], max_length=255, null=True, verbose_name='content_type')),
                ('send_from', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.senders')),
            ],
            options={
                'verbose_name': 'notification_template',
                'verbose_name_plural': 'notification_templates',
                'db_table': 'notify"."templates_notify',
            },
        ),
        migrations.AddIndex(
            model_name='templatesbody',
            index=models.Index(fields=['title'], name='body_templates_title_idx'),
        ),
        migrations.AddField(
            model_name='recipients',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.notifications'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='body',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.templatesbody'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notify',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='notify.templatesnotify'),
        ),
    ]
