# Generated by Django 3.2.16 on 2022-10-28 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(verbose_name='address')),
                ('source', models.CharField(choices=[('mail', 'mail'), ('sms', 'sms'), ('telegram', 'telegram'), ('viber', 'viber'), ('whatsapp', 'whatsapp'), ('push', 'push')], max_length=255, verbose_name='source')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='subject')),
                ('text', models.TextField(verbose_name='text')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='send at')),
                ('status', models.CharField(choices=[('wait', 'wait'), ('processing', 'processing'), ('success', 'success'), ('failed', 'failed')], default='wait', max_length=255, verbose_name='status')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'notify"."messages',
            },
        ),
    ]
