"""Add user agent column

Revision ID: 246f18fe10bb
Revises: d625dffe3025
Create Date: 2022-08-30 14:11:47.603669

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '246f18fe10bb'
down_revision = 'd625dffe3025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_record', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_record', 'user_agent')
    # ### end Alembic commands ###
