"""Enrich table for user logins

Revision ID: 61ebe7629878
Revises: cf1382f29440
Create Date: 2022-08-30 10:41:45.116695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '61ebe7629878'
down_revision = 'cf1382f29440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_record', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('user_login_record', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('user_login_record', sa.Column('login_at', sa.DateTime(), nullable=True))
    op.drop_column('user_login_record', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_record', sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user_login_record', 'login_at')
    op.drop_column('user_login_record', 'refresh_token')
    op.drop_column('user_login_record', 'access_token')
    # ### end Alembic commands ###
