"""Add role tables

Revision ID: d625dffe3025
Revises: 61ebe7629878
Create Date: 2022-08-30 13:39:37.573006

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd625dffe3025'
down_revision = '61ebe7629878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['login'])
    op.alter_column('user_login_record', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_login_record', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_login_record', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_login_record', 'login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_record', 'login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_login_record', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_login_record', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_login_record', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_table('user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
