version: '3'

services:

  ugc-nginx:
    container_name: ugc-nginx
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      -  ugc-nginx_log:/var/log/nginx/
    ports:
      - "${NGINX_LOCAL_PORT}:80"
    depends_on:
      - ugc-api
    networks:
      - backend
      
  ugc-etl:
    container_name: ugc-etl
    build: ./etl
    env_file:
      - ./etl/.env
    environment:
      ch_host: "ugc-clickhouse-node1"
      ch_port: ${CH_LISTEN_TCP_PORT}
      kafka_uri: '["${KAFKA_BROKER_URL}"]'
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-etl
    networks:
      - backend

  ugc-api:
    container_name: ugc-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILENAME=requirements.txt
        - EXPOSE_PORT=${API_LISTEN_PORT}
    restart: always
    volumes:
      - ./api:/app
    entrypoint: gunicorn wsgi_app:app -b ${API_LISTEN_HOST}:${API_LISTEN_PORT} -w 2 --log-level debug --reload --timeout 0
    env_file:
      - ./api/.env
    environment:
      APP_HOST: ${API_LISTEN_HOST}
      APP_PORT: ${API_LISTEN_PORT}
      SWAGGER_HOST: "localhost:${API_LOCAL_PORT}"
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      MONGO_DSN: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@ugc-mongo:${MONGO_CONTAINER_PORT}"
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-api
    networks:
      - backend

  ugc-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_LOCAL_PORT}:${MONGO_CONTAINER_PORT}"
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-mongo
    networks:
      - backend

  ugc-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${ME_LOCAL_PORT}:${ME_CONTAINER_PORT}"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-mongo-express
    networks:
      - backend

  ugc-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: ugc-zookeeper
    container_name: ugc-zookeeper
    ports:
      - "${ZOOKEEPER_LOCAL_PORT}:${ZOOKEEPER_CONTAINER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CONTAINER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-zookeeper
    networks:
      - backend

  ugc-zookeeper_ch:
    image: zookeeper:3.5
    container_name: ugc-zookeeper_ch
    hostname: ugc-zookeeper_ch
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-zookeeper_ch
    networks:
      - backend

  ugc-clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: ugc-clickhouse-node1
    hostname: ugc-clickhouse-node1
    ports:
      - "${CH_HTTP_LOCAL_PORT}:${CH_LISTEN_HTTP_PORT}"
      - "${CH_TCP_LOCAL_PORT}:${CH_LISTEN_TCP_PORT}"
    volumes:
      - ./ch_conf/node1:/etc/clickhouse-server
    depends_on:
      - ugc-zookeeper_ch
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-clickhouse-node1
    networks:
      - backend

  ugc-clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: ugc-clickhouse-node2
    hostname: ugc-clickhouse-node2
    volumes:
      - ./ch_conf/node2:/etc/clickhouse-server
    depends_on:
      - ugc-zookeeper_ch
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-clickhouse-node2
    networks:
      - backend

  ugc-clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: ugc-clickhouse-node3
    hostname: ugc-clickhouse-node3
    volumes:
      - ./ch_conf/node3:/etc/clickhouse-server
    depends_on:
      - ugc-zookeeper_ch
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-clickhouse-node3
    networks:
      - backend

  ugc-clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: ugc-clickhouse-node4
    hostname: ugc-clickhouse-node4
    volumes:
      - ./ch_conf/node4:/etc/clickhouse-server
    depends_on:
      - ugc-zookeeper_ch
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-clickhouse-node4
    networks:
      - backend

  ugc-broker:
    image: confluentinc/cp-server:7.2.1
    hostname: ugc-broker
    container_name: ugc-broker
    depends_on:
      - ugc-zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "ugc-zookeeper:${ZOOKEEPER_CONTAINER_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER_URL},PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://${KAFKA_SR_HOST_NAME}:${KAFKA_SR_CONTAINER_PORT}
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_URL}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_LOG_RETENTION_MINUTES: 5
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-broker
    networks:
      - backend

  ugc-schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: ugc-schema-registry
    container_name: ugc-schema-registry
    depends_on:
      - ugc-broker
    ports:
      - "KAFKA_SR_LOCAL_PORT:${KAFKA_SR_CONTAINER_PORT}"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: ${KAFKA_SR_HOST_NAME}
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_URL}
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:${KAFKA_SR_CONTAINER_PORT}
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-schema-registry
    networks:
      - backend

  ugc-connect:
    image: cnfldemos/cp-server-connect-datagen:0.6.0-7.2.1
    hostname: ugc-connect
    container_name: ugc-connect
    depends_on:
      - ugc-broker
      - ugc-schema-registry
    ports:
      - "${KAFKA_CONNECT_LOCAL_PORT}:${KAFKA_CONNECT_CONTAINER_PORT}"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_URL}
      CONNECT_REST_ADVERTISED_HOST_NAME: ugc-connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://${KAFKA_SR_HOST_NAME}:${KAFKA_SR_CONTAINER_PORT}
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.2.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-connect
    networks:
      - backend

  ugc-control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1
    hostname: ugc-control-center
    container_name: ugc-control-center
    depends_on:
      - ugc-broker
      - ugc-schema-registry
    ports:
      - "${KAFKA_CC_LOCAL_PORT}:${KAFKA_CC_CONTAINER_PORT}"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_URL}
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: "ugc-connect:${KAFKA_CONNECT_CONTAINER_PORT}"
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://${KAFKA_SR_HOST_NAME}:${KAFKA_SR_CONTAINER_PORT}"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: ${KAFKA_CC_CONTAINER_PORT}
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}
        tag: ugc-control-center
    networks:
      - backend

  filebeat:
    image: elastic/filebeat:7.10.1
    environment:
      LOGSTASH_ADDRESS: ${LOGSTASH_ADDRESS}
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ugc-nginx_log:/var/log/nginx:ro
      - ./logging/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - ugc-nginx
    networks:
      - backend


volumes:
  ugc-nginx_log:

networks:
  backend:
    name: ${DOCKER_NETWORK_NAME}
    external: true