version: '3'

services:

  admin_notify: # -------------------------------------------------------------------
    build: ./
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      
  db_notify: # --------------------------------------------------------------------
    image: postgres:13-alpine
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  nginx_notify: # -----------------------------------------------------------------
    build: ./nginx
    ports:
      - 80:80
    volumes:
        - static_volume:/static
    restart: always
    depends_on:
      - admin_notify

volumes:
  static_volume:
  